import { LayoutProvider } from '@/components/LayoutProvider'
import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'MKS Sistemas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
